## Linear Regression ?
- Let's first create our loss function
- Error(m, b) = 1/n (i=1 ~ n)(Actual output - predicted output)**2


In [15]:
# Import basic necessities
import pandas as pd
import os
import numpy as np

import tensorflow as tf
from tensorflow import keras

from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

In [16]:
drivers_df = pd.read_csv("ready_db/drviers.csv")
drivers_df.head()

DRIVER_ID  GENDER  CREDIT_SCORE   AGE  VEHICLE_ID
0          1     2.0           824  27.0     7420963
1          2     1.0           824  28.0     7420963
2          3     2.0           666  51.0     7396448
3          4     2.0           666  34.0     6208988
4          5     2.0           824  88.0     6078430

In [17]:
drivers_df = drivers_df.dropna()
drivers_df = drivers_df.drop(columns='DRIVER_ID')
drivers_df = drivers_df.drop(columns='GENDER')

In [18]:
drivers_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 726 entries, 0 to 735
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   CREDIT_SCORE  726 non-null    int64  
 1   AGE           726 non-null    float64
 2   VEHICLE_ID    726 non-null    int64  
dtypes: float64(1), int64(2)
memory usage: 22.7 KB


In [19]:
# Remove creadit score outcome target from fetures data
y = drivers_df['CREDIT_SCORE']
X = drivers_df.drop(columns='CREDIT_SCORE')

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [21]:
# The PCA algorithem is going to standardize the input data frame, calculate teh covariance matrix of the features
# eigenvector - covariance matrix of the features can be avaraged by generating another vector (pointer)
# distance form one point to another (pointer length) eigenvalues
# PCA shows : What number of principal components we need.
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)
fit = pca.fit(X_scaled)
print(f"Explained Variance: {fit.explained_variance_ratio_}")
print(fit.components_)

Explained Variance: [0.56633646 0.43366354]
[[ 0.99987035  0.01610224]
 [ 0.01610224 -0.99987035]]


In [22]:
# The purpose of the ExtraTreesClassifier is to fit a number of randomized decision trees to the data, from of ensemble learning
# Particularly, random splits of all observations are carried out to ensure that the model does not overfit the data.
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(X, y)
# The importans of a feature is computed as the (normalized) Total reduction of the criterion brough by that feature.
print(model.feature_importances_)

[0.42608708 0.57391292]


In [23]:
# Credit depending on your car own (independent) 
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)
y_pred = model.predict(X)
print(y_pred)

[778.48372313 778.02673621 766.72917358 736.3837812  707.51593806
 732.24824348 736.48719846 780.6152651  707.51593806 741.92701193
 739.22332062 780.6152651  729.23606367 775.76158165 780.6152651
 780.6152651  780.6152651  736.3837812  736.05442603 728.508176
 733.76949143 726.2232414  736.05442603 728.508176   733.76949143
 726.2232414  747.90579157 737.97297915 782.19017961 738.88695299
 783.10415345 737.97297915 782.19017961 738.88695299 783.10415345
 737.97297915 782.19017961 738.88695299 783.10415345 737.97297915
 782.19017961 738.88695299 783.10415345 737.97297915 782.19017961
 738.88695299 783.10415345 737.97297915 782.19017961 738.88695299
 783.10415345 734.24460287 727.0559612  736.43695277 727.0559612
 736.43695277 724.69595917 769.14855582 772.97655633 759.72393562
 736.58229195 743.52836084 757.69495539 762.48922393 729.74719844
 763.86018469 731.1181592  762.48922393 729.74719844 763.86018469
 731.1181592  762.48922393 729.74719844 763.86018469 731.1181592
 762.48922393 7

### NOTE: :Since the importances of feature isn't a good, so we need to run the Feature Selection Technique with additional input on the fields... next step.

In [26]:
#Let's test
x_7420963 = np.array([28, 7420963]).reshape(-1,2)
x_7420963

array([[     28, 7420963]])

In [27]:
model.predict(x_7420963)

array([778.02673621])