## Multivariate Linear Regression ?
-  Output y is dependent on more than one independent variable
-  Linear hyper plane is used for predict y
- y =f(x) = b + w1x1 + w2x2 + ... wnxn = (ni=1 ~ n)wixi
- cost function reamins the same

# RANDOM FOREST, KNN - lazy learner - Choice : RANDOM FOREST
- SVMs are another ML classifier (Logistic Regression)
- Our aim is to create a hyper plane decision boundary between classes in the best way.
- / best separater is Optimal Hyperplane - with maximum margin
- Suport vertors are the points that reside closest to the hyperplan
- influences hyper plane
- linear + sigmoid to squash range 0 to 1 to minimize cost function.

- What about non-linear? do the Kernel Trick - take a low dimensional (2D) transforms it into a higher dimensional space.
 - Decision tree Root Node branch < or >=  ---> can use multiple classes just branch more  out
  - Root?  and How get us the boundaries?
  - let's say 7 different credit score - data can divided to ? 
  - Use Gini initial impurity to Gini Gain Calculation 
  - Ginit = (i=1 to C) pi(1-pi) c-number of classes Pi - probability of reandomly choose element of class i
  - e.g c = 7 p(1) = a_class_total/entire_set_total
  - from there we split the branches into two section left and right - which will generate G = (i=1 to C) pi(1-pi) where c is
  - each G move the split to the highest
  
  - KNN  - Popular ML with decent performance - it is called a lazy learner because it doesn't have a training phase
  - It compute training data directly
  - which makes it a non-parametric algorithm
   - pre set value of K  and calculate K point to other point , sort the distances, choose the top row.
   - BAD BAD - because it doesn't have the training set, we have to load all the traiing data to calculate the points.
   - high memory usage, to aid, we scale the input data using Euclidean Distance or Cosine Distance.
   - Large number of features, it is known as "Curse of Dimensionality


In [2]:
# Import basic necessities
import pandas as pd
import os
import numpy as np

import tensorflow as tf
from tensorflow import keras

from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

C:\Users\ntissk01\Anaconda3\envs\mlenv\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 80 from C header, got 88 from PyObject
  return f(*args, **kwds)


In [3]:
drivers_df = pd.read_csv("ready_db/drviers.csv")
drivers_df.head()

DRIVER_ID  GENDER  CREDIT_SCORE   AGE  VEHICLE_ID
0          1     2.0           824  27.0     7420963
1          2     1.0           824  28.0     7420963
2          3     2.0           666  51.0     7396448
3          4     2.0           666  34.0     6208988
4          5     2.0           824  88.0     6078430

In [4]:
#drop only index colum which is Driver id
drivers_df = drivers_df.dropna()
drivers_df = drivers_df.drop(columns='DRIVER_ID')
drivers_df.head()

GENDER  CREDIT_SCORE   AGE  VEHICLE_ID
0     2.0           824  27.0     7420963
1     1.0           824  28.0     7420963
2     2.0           666  51.0     7396448
3     2.0           666  34.0     6208988
4     2.0           824  88.0     6078430

In [5]:
# Remove creadit score outcome target from fetures data
y = drivers_df['CREDIT_SCORE']
X = drivers_df.drop(columns='CREDIT_SCORE')

from sklearn.linear_model import LinearRegression
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [6]:
# Fitting Polynomial Regression to the data set
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [7]:
# Setup the first data as input
test_data = np.array([1,27,7420963])
test_data = test_data.reshape(-1, 3)
test_data = test_data.astype(float)

In [8]:
# Try the first data outcome - actual score is 824 - a bit off
model.predict(test_data)[0]

768.040832355666

In [10]:
# Fitting KNN, RF, run Classification Report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [11]:
# 26 % isn't good - NO !!!!!!
LR_clf = LogisticRegression()
LR_model = LR_clf.fit(X_train, y_train)
LR_prediction = LR_clf.predict(X_test)
print(accuracy_score(LR_prediction, y_test))
print(confusion_matrix(LR_prediction, y_test))
print(classification_report(LR_prediction, y_test))

0.26373626373626374
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  3  1  1  1 33  1 48  8  1 54 26]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
              precision    recall  f1-score   support

         321       0.00      0.00      0.00         0
         392       0.00      0.00      0.00         0


In [12]:
# BINGO!!!!!!!!!!!!!!
RF_clf = RandomForestClassifier()
RF_model = RF_clf.fit(X_train, y_train)
RF_prediction = RF_clf.predict(X_test)
print(accuracy_score(RF_prediction, y_test))
print(confusion_matrix(RF_prediction, y_test))
print(classification_report(RF_prediction, y_test))

0.6263736263736264
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  1  0  0  0 17  1  8  3  1  9  0  3]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  2  0  0  0  0  9  0 37  0  0 12  0  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  

In [14]:
# Similar to Logistic
SVM_clf = SVC()
SVM_model = SVM_clf.fit(X_train, y_train)
SVM_prediction = SVM_clf.predict(X_test)
print(accuracy_score(SVM_prediction, y_test))
print(confusion_matrix(SVM_prediction, y_test))
print(classification_report(SVM_prediction, y_test))

0.26373626373626374
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  0  0  1  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  1  0  3  1  0  0  1 33  1 48  8  1 53 26]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
              precision    recall  f1-score   support

      

In [15]:
# Similar to Random Forest
KNN_clf = KNeighborsClassifier()
KNN_model = KNN_clf.fit(X_train, y_train)
KNN_prediction = KNN_clf.predict(X_test)
print(accuracy_score(KNN_prediction, y_test))
print(confusion_matrix(KNN_prediction, y_test))
print(classification_report(KNN_prediction, y_test))


0.6153846153846154
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  1  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  3  0  0  0  0 19  0  8  4  1 12  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0  