## Feature selection ?
- Simple modles are easier to interpret
- Shorter training times
- Enhanced generalisation by reducing overfitting
- Easier to implement
- Reduced risk of data errors during model use
- Variable redundancy
- Bad learning behavior in high dimensional Space

In [1]:
# Import basic necessities
import pandas as pd
import os
import numpy as np

import tensorflow as tf
from tensorflow import keras

from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

In [2]:
drivers_df = pd.read_csv("ready_db/drviers.csv")
drivers_df.head()

DRIVER_ID  GENDER  CREDIT_SCORE   AGE  VEHICLE_ID
0          1     2.0           824  27.0     7420963
1          2     1.0           824  28.0     7420963
2          3     2.0           666  51.0     7396448
3          4     2.0           666  34.0     6208988
4          5     2.0           824  88.0     6078430

In [3]:
drivers_df = drivers_df.dropna()
drivers_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 726 entries, 0 to 735
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   DRIVER_ID     726 non-null    int64  
 1   GENDER        726 non-null    float64
 2   CREDIT_SCORE  726 non-null    int64  
 3   AGE           726 non-null    float64
 4   VEHICLE_ID    726 non-null    int64  
dtypes: float64(2), int64(3)
memory usage: 34.0 KB


In [4]:
# Remove creadit score outcome target from fetures data
y = drivers_df['CREDIT_SCORE']
X = drivers_df.drop(columns='CREDIT_SCORE')

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [9]:
# The PCA algorithem is going to standardize the input data frame, calculate teh covariance matrix of the features
# eigenvector - covariance matrix of the features can be avaraged by generating another vector (pointer)
# distance form one point to another (pointer length) eigenvalues
# PCA shows : What number of principal components we need.
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)
fit = pca.fit(X_scaled)
print(f"Explained Variance: {fit.explained_variance_ratio_}")
print(fit.components_)

Explained Variance: [0.62957741 0.21252828 0.0907765  0.06711781]
[[ 0.02022812 -0.99889819  0.02673549 -0.03283978]
 [ 0.99244598  0.02456926  0.02190943 -0.11818337]
 [-0.01652614  0.02469284  0.99823537  0.05141295]
 [-0.11986948  0.03144884  0.04828386 -0.99111601]]


In [10]:
# The purpose of the ExtraTreesClassifier is to fit a number of randomized decision trees to the data, from of ensemble learning
# Particularly, random splits of all observations are carried out to ensure that the model does not overfit the data.
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(X, y)
# The importans of a feature is computed as the (normalized) Total reduction of the criterion brough by that feature.
print(model.feature_importances_)

[0.40072068 0.04281098 0.30998234 0.246486  ]


### NOTE: :Since the importances of feature isn't a good, so we need to run the Feature Selection Technique with additional input on the fields... next step.